runtime: python37

automatic_scaling:
  max_instances: 1

handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /call
    script: auto
    secure: always

  - url: /.*
    static_files: static/main.html
    upload: static/main.html
    secure: always
